# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-b6NIgkoF0_5ORi9i6e5-ghBJCLPO6fw
"""

#1.Importing necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

#2.loading the datset
iris=load_iris()
x=iris.data   # Input feature
y=iris.target #target Labels


#3.splitting into training and testing(80%-traaining,20%-testing)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#4.Building the model & training the data
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

#5.Making predictions
y_pred=model.predict(x_test)

#6.Calculating the accuracy with the original & Predicted
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy",accuracy)

#7.Plotting the tree
plt.figure(figsize=(10,6))
plot_tree(model,filled=True,feature_names=iris.feature_names,class_names=iris.target_names)
plt.savefig("tree_visual.png",dpi=300,bbox_inches='tight')
plt.show()